# Generated by Django 5.2.11 on 2026-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Résumé original')),
                ('tone', models.CharField(choices=[('professionnel', 'Professionnel'), ('inspirant', 'Inspirant'), ('storytelling', 'Storytelling'), ('educatif', 'Éducatif'), ('humoristique', 'Humoristique')], default='professionnel', max_length=20)),
                ('generated_content', models.TextField(verbose_name='Contenu généré')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post généré',
                'verbose_name_plural': 'Posts générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte LinkedIn',
                'verbose_name_plural': 'Comptes LinkedIn',
            },
        ),
    ]
