# Generated by Django 5.2.11 on 2026-02-11 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generatedpost_user_linkedinaccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu du post')),
                ('scheduled_at', models.DateTimeField(verbose_name='Date de publication prévue')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('published', 'Publié'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post programmé',
                'verbose_name_plural': 'Posts programmés',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
