# Generated by Django 5.2.11 on 2026-02-11 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scheduledpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_tone', models.CharField(choices=[('professionnel', 'Professionnel'), ('inspirant', 'Inspirant'), ('storytelling', 'Storytelling'), ('educatif', 'Éducatif'), ('humoristique', 'Humoristique')], default='professionnel', max_length=20)),
                ('prompt_prefix', models.TextField(blank=True, help_text='Texte ajouté au début du résumé', verbose_name='Préfixe du prompt')),
                ('prompt_suffix', models.TextField(blank=True, help_text='Texte ajouté à la fin du résumé', verbose_name='Suffixe du prompt')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de prompt',
                'verbose_name_plural': 'Templates de prompts',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
