# Generated by Django 5.2.11 on 2026-02-11 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prompttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_post_id', models.CharField(blank=True, max_length=100, verbose_name='ID du post LinkedIn')),
                ('content', models.TextField(verbose_name='Contenu du post')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('views', models.IntegerField(default=0, verbose_name='Vues')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('comments', models.IntegerField(default=0, verbose_name='Commentaires')),
                ('shares', models.IntegerField(default=0, verbose_name='Partages')),
                ('has_images', models.BooleanField(default=False, verbose_name='Contient des images')),
                ('tone', models.CharField(blank=True, max_length=20, verbose_name='Ton utilisé')),
                ('stats_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière MAJ des stats')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post publié',
                'verbose_name_plural': 'Posts publiés',
                'ordering': ['-published_at'],
            },
        ),
    ]
