# Generated by Django 5.2.11 on 2026-02-16 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_publishedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Rôle / Poste')),
                ('industry', models.CharField(blank=True, max_length=200, verbose_name="Secteur d'activité")),
                ('expertise', models.TextField(blank=True, verbose_name="Domaines d'expertise")),
                ('target_audience', models.TextField(blank=True, verbose_name='Audience cible')),
                ('writing_style', models.TextField(blank=True, verbose_name="Style d'écriture")),
                ('bio', models.TextField(blank=True, verbose_name='Bio / Description')),
                ('example_posts', models.TextField(blank=True, verbose_name='Exemples de posts')),
                ('additional_context', models.TextField(blank=True, verbose_name='Contexte additionnel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
