# Generated by Django 5.2.11 on 2026-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='images_data',
            field=models.JSONField(blank=True, default=list, help_text='Liste de {data: base64, mime_type: str}', verbose_name='Images en base64'),
        ),
    ]
