# Generated by Django 5.2.11 on 2026-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_images_data_to_scheduledpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Clé de session anonyme'),
        ),
    ]
