# Generated by Django 5.2.11 on 2026-02-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_session_key_to_generatedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='headline',
            field=models.CharField(blank=True, max_length=500, verbose_name='Titre/Headline LinkedIn'),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Photo de profil'),
        ),
    ]
