# Generated by Django 5.2.12 on 2026-03-10 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_subscription_usagerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_description', models.TextField(verbose_name="Description de l'apparence")),
                ('avatar_base64', models.TextField(verbose_name='Avatar cartoon (base64)')),
                ('avatar_mime_type', models.CharField(default='image/jpeg', max_length=50)),
                ('source_photo_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartoon_avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar cartoon',
                'verbose_name_plural': 'Avatars cartoon',
            },
        ),
        migrations.CreateModel(
            name='CartoonUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('cartoon_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoon_usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage cartoon mensuel',
                'verbose_name_plural': 'Usages cartoon mensuels',
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
